config/routes.rb
Rails.application.routes.draw do
  resources :people

  root 'people#new'

end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @daysAlive = (Date.today - @person.DOB).to_i

    @martianDaysAlive = ((Date.today - @person.DOB) / 1.03).to_i

  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create

    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:DOB, :Name, :CreatedAt, :Surname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Person Age</title>
      <%= render partial: 'shared/header' %>
</head>
<body>
  <div class="navbar-wrapper clearfix">
    <%= render partial: 'shared/navbar' %>
  </div>


<div class="content-wrapper">

  <div class="container container-main">
    <%= yield %>
  </div>

</div>

    <%= render partial: 'shared/footer' %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Date of Birth' , class:'control-label'%><br>
    <div class="row">

      <div class="col-md-4">
        <%= f.date_select :DOB,  {:date_separator => '</div><div class="col-md-4">', :start_year => Date.today.year - 110, :end_year => Date.today.year  }, { :class => "form-control" } %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :Name %><br>
    <div class="row">
    <div class="col-sm-6 col-md-4">

      <%= f.text_field :Name, class: "form-control" %>
    </div>
    </div>
  </div>


  <div class="form-group">
    <%= f.label :Surname %><br>
    <div class="row">
    <div class="col-sm-6 col-md-4">

      <%= f.text_field :Surname, class: "form-control" %>
    </div>
    </div>
  </div>


  <div class="actions">
    <%= f.submit 'Find out now', class: "btn btn-default" %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Date of Birth</th>
      <th>Name</th>
      <th>Surname</th>
      <th>Created on</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.DOB %></td>
        <td><%= person.Name %></td>
        <td><%= person.Surname %></td>
        <td><%= person.created_at %></td>
        <td style="text-align:right;">
          <%= link_to ("<span class='glyphicon glyphicon-link'></span>").html_safe, person, class: "btn btn-default"%>
          <%= link_to ("<span class='glyphicon glyphicon-edit'></span>").html_safe, edit_person_path(person), class: "btn btn-primary" %>
          <%= link_to ("<span class='glyphicon glyphicon-trash'></span>").html_safe, person, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path, class:'btn btn-default' %>

app/views/people/new.html.erb
<h1>How many days have you been alive?</h1>

<%= render 'form' %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @person.Name %> <%= @person.Surname %> has been alive for</h3>
<h2><%= @daysAlive %> Day<% if(@daysAlive != 1) %>s<%end%></h2>
<h2><%= @martianDaysAlive %> Martian day<% if(@daysAlive != 1) %>s<%end%></h2>

<p>
  <strong>You were born:</strong>
  <%= @person.DOB %>
</p>

<p>
  <strong>Name:</strong>
  <%= @person.Name %>
</p>
<p>
  <strong>Surname:</strong>
  <%= @person.Surname %>
</p>

<p>
  <strong>Submitted at:</strong>
  <%= @person.created_at %>
</p>

<%= link_to 'Lets try another', root_path, class:"btn btn-default" %>

app/views/shared/_footer.html.erb
  <footer>
  <div class="container">
    <div class="row">
    <div class="col-sm-9 footer-category">
      <ul style="list-style:none;padding:0;">
        <li><strong>What is this? </strong></li>
        <li><p>This website is to satisfy the requirements for the Software Deployment and Evolution Assignment 1</p></li>
      </ul>

    </div>
      <div class="col-sm-3 footer-category">
        <ul style="list-style:none;padding:0;">
          <li><strong>Team Members</strong></li>
          <li>John Stableford</li>
          <li>Stephanie Baker</li>
          <li>James Kernaghan</li>
        </ul>

      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
    <meta charset="utf-8">
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
    <%# favicon_link_tag '/assets/favicon.ico' %>
<link href="/assets/favicon.ico" rel="shortcut icon" type="image/x-icon" />


  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>


  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>




  <%= csrf_meta_tags %>
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1" name="viewport">

app/views/shared/_loading.html.erb
<div id="site-loader" class="">
	<div id="loader-box">
		<div class="spinner-icon">

			<div class="spincontainer line1">
				<div>
				</div>
			</div>

			<div class="spincontainer line2">
				<div>
				</div>
			</div>

			<div class="spincontainer line3">
				<div>
				</div>
			</div>

			<div class="spincontainer line4">
				<div>
				</div>
			</div>

		</div>
	</div>
</div>

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="padding-top:0;padding-bottom:0;">
        <a class="navbar-brand" href="/">
          <span class="glyphicon glyphicon-globe"></span>
          Person Age
        </a>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="/" alt="New User">
            <span class="glyphicon glyphicon-plus"></span>
            <span class="glyphicon glyphicon-user"></span>
          </a>
        </li>
        <li><a href="/people" alt="list users">
          <span class="glyphicon glyphicon glyphicon-th-list"></span>
          <span class="glyphicon glyphicon-user"></span>
      </a></li>

      </ul>





    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
	<%= render partial: 'shared/loading' %>